# Generated by Django 5.0.6 on 2024-07-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleNoteSecond', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplenotesecond',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='simplenotesecond',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='simplenotesecond',
            name='location',
        ),
    ]
